---
title: 'Data Science - Homework #5'
author: "Jon Brock - JPB2210"
output: 
    github_document:
        toc: TRUE
        toc_depth: 2
---

```{r load packages, message = FALSE}
library(tidyverse)
```

***

## Problem #1
###### (*20 points*)
##### *Writing a function*

```{r initial code input}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```


```{r writing function}
species_replace <- function(x, y) {
    
    pull(x, y) %>% replace_na("virginica")
    
}

species_replace(iris_with_missing, "Species")
```

***

## Problem #2
###### (*25 points*)
##### *Tidy and plot longitudinal data*

```{r iteration of reading csv files, message = FALSE, warning = FALSE}
csv_files <- list.files("./data", pattern = "*.csv", full.names = TRUE) %>%  
    set_names(nm = basename(.)) %>% 
    map_df(read_csv, col_names = TRUE, col_types = cols(), .id = "filename") %>% 
    mutate(
        arm = str_sub(filename, 1,3),
        id = str_sub(filename, 5,6)) %>% 
    select(arm, id, week_1:week_8)


csv_files
```

***

## Problem #3
###### (*35 points*)
##### *Create and plot simulations*

```{r}

```

***

## Homework Resources  

*Given the enormous headache of trying to figure out this homework, I relied much more heavily on online resources than previous homeworks. I felt it necessary to cite all of my resources. They are listed below.*  

[https://www.gerkelab.com/blog/2018/09/import-directory-csv-purrr-readr/]()  
[https://serialmentor.com/blog/2016/6/13/reading-and-combining-many-tidy-data-files-in-R]()  
[https://www.hvitfeldt.me/blog/purrr-tips-and-tricks/#sources]()  
[https://github.com/STAT545-UBC/Discussion/issues/398]()  
[https://gist.github.com/ColinFay/d74d331825868b181860212cd1577b69]()  
[https://gist.github.com/ColinFay/d74d331825868b181860212cd1577b69]()  
[https://lsru.github.io/tv_course/TD_purrr_solution.html]()